const Types = Object.freeze({
  SET_NAME: 'SET_NAME',
  SET_COLORS: 'SET_COLORS',
  SET_TYPOGRAPHY: 'SET_TYPOGRAPHY',
  SET_COMPONENTS: 'SET_COMPONENTS',
  GET_FONTLIST: 'GET_FONTLIST',
  GET_ID: 'GET_ID',
  UPDATE_STATE: 'UPDATE_STATE',
  IS_SAVING: 'IS_SAVING',
});

export default Types;
